services:

     iam_postgres:
       image: postgres
       hostname: iam_postgres
       restart: always
       environment:
         POSTGRES_DB: ${IAM_SERVICE_POSTGRES_DB}
         POSTGRES_USER: ${IAM_SERVICE_POSTGRES_USER}
         POSTGRES_PASSWORD: ${IAM_SERVICE_POSTGRES_PASSWORD}
       volumes:
         - pg-data:/var/lib/postgresql/data
       ports:
         - "5432:5432"
       networks: 
         - s3ng-net

     iam_service:
       image: ${DOCKER_REGISTRY-}iam_service
       environment:
         "DOTNET_ENVIRONMENT": "Development"
       build:
         context: ./IAM
         dockerfile: Dockerfile
       ports:
         - "50051:50051"
       networks: 
         - s3ng-net

     webhost:
       image: ${DOCKER_REGISTRY-}webhost
       environment:
         "IAM_SERVICE_URI": ${IAM_SERVICE_URI}
         "DOTNET_ENVIRONMENT": "Development"
       build:
         context: .
         dockerfile: WebHost/Dockerfile
       ports:
         - "8080:8080"
       networks: 
         - s3ng-net


volumes:
  pg-data:
  pg-admin:
    driver: local

networks:
  s3ng-net:
    driver: bridge