version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  webhost:
    image: ${DOCKER_REGISTRY-}webhost
    build:
      context: .
      dockerfile: ApiGateway/WebHost/Dockerfile
    environment:
      USER_SERVICE_URI: ${USER_SERVICE_URI}
      DOTNET_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
    networks:
      - app-network

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Services/UserService/UserService.Application/Dockerfile
    ports:
      - "5005:5005"
    networks:
      - app-network
    depends_on:
      - userpostgres

  userpostgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${USER_SERVICE_POSTGRES_DB}
      POSTGRES_USER: ${USER_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data: